#!/bin/bash

# lein run --output "/tmp/lcp-demo-1.jpg" --tile-size 20 --step-size 20 --width 100 --samples 3 ~/Downloads/demo/dragonfly.jpg ~/Downloads/demo/tiles/*
# lein run --output "/tmp/lcp-demo-2.jpg" --tile-size 40 --step-size 20 --width 70 --samples 3 ~/Downloads/demo/dragonfly.jpg ~/Downloads/demo/tiles/*
lein run --output "/tmp/lcp-demo-3.jpg" --tile-size 40 --step-size 10 --width 50 --samples 3 ~/Downloads/demo/dragonfly.jpg ~/Downloads/demo/tiles2/*
